default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('DB_MAX_POOL') { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { '3306' } %>
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'nozomi_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'nozomi_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'nozomi_production' } %>
